# Generated by Django 5.2.4 on 2025-08-07 07:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre.'}, help_text='Requerido. 150 caracteres o menos. Letras, números, espacios y @/./+/-/_ únicamente.', max_length=150, unique=True, validators=[users.models.CustomUnicodeUsernameValidator()]),
        ),
    ]
